# Generated by Django 4.2 on 2024-07-16 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('typ', models.IntegerField(choices=[(0, '珠'), (1, '链'), (2, '其他')], verbose_name='类别')),
                ('pic', models.ImageField(upload_to='component/', verbose_name='图片')),
                ('loc', models.CharField(max_length=50, verbose_name='产地')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
            ],
            options={
                'verbose_name': '零件',
                'verbose_name_plural': '零件',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('pic', models.ImageField(upload_to='product/', verbose_name='图片')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
                ('sales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量')),
                ('component', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*[^\\|]+\\|)*(\\d+\\*[^\\|]+)$', '请用这样的格式来表示产品的组成: 3*塑料石|2*蓝宝石|1*玉髓手环')], verbose_name='零件组成\n示例: 3*塑料石|2*蓝宝石|1*玉髓手环')),
            ],
            options={
                'verbose_name': '成品',
                'verbose_name_plural': '成品',
            },
        ),
    ]
