# Generated by Django 4.2 on 2024-07-17 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('typ', models.CharField(choices=[('单圈', '单圈'), ('双圈', '双圈'), ('其他', '其他')], max_length=20, verbose_name='类别')),
                ('pic', models.ImageField(upload_to='gemstone/', verbose_name='图片')),
                ('loc', models.CharField(max_length=50, verbose_name='产地')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
            ],
            options={
                'verbose_name': '手链',
                'verbose_name_plural': '手链',
            },
        ),
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('typ', models.CharField(choices=[('珠', '珠'), ('其他', '其他')], max_length=20, verbose_name='类别')),
                ('pic', models.ImageField(upload_to='gemstone/', verbose_name='图片')),
                ('loc', models.CharField(max_length=50, verbose_name='产地')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
            ],
            options={
                'verbose_name': '珠',
                'verbose_name_plural': '珠',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('typ', models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, verbose_name='类别')),
                ('pic', models.ImageField(upload_to='gift/', verbose_name='图片')),
                ('intro', models.CharField(max_length=100, verbose_name='简介')),
                ('detail', models.TextField(verbose_name='详细介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
                ('sales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量')),
                ('component', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*[^\\|]+\\|)*(\\d+\\*[^\\|]+)$', '请用这样的格式来表示产品的组成: 3*塑料石|2*蓝宝石|1*玉髓手环')], verbose_name='组成\n示例: 3*塑料石|2*蓝宝石|1*玉髓手环')),
            ],
            options={
                'verbose_name': '挚礼',
                'verbose_name_plural': '挚礼',
            },
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
