# Generated by Django 4.2 on 2024-07-14 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_component_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='loc',
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(1)], verbose_name='零件组成(3*塑料石|2*蓝宝石|1*玉髓手环)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(upload_to='product/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价'),
        ),
    ]
