# Generated by Django 4.2 on 2024-07-14 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_loc_alter_component_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(^\\d+\\*[^|]+$\\|)*^\\d+\\*[^|]+$$', '请用这样的格式来表示产品的组成: "3*塑料石|2*蓝宝石|1*玉髓手环"')], verbose_name='零件组成(3*塑料石|2*蓝宝石|1*玉髓手环)'),
        ),
    ]
