# Generated by Django 4.2 on 2024-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='pic',
            field=models.ImageField(upload_to='bracelet/', verbose_name='图片'),
        ),
    ]
