# Generated by Django 4.2 on 2024-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_bracelet_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='typ',
            field=models.CharField(choices=[('宝石', '宝石'), ('其他', '其他')], max_length=20, verbose_name='类别'),
        ),
    ]
