# Generated by Django 4.2 on 2024-08-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_gift_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracelet',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='gemstone',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='pic',
        ),
        migrations.AddField(
            model_name='bracelet',
            name='cover',
            field=models.ImageField(null=True, upload_to='bracelet/', verbose_name='封面图片（其他图片在下方关联模型里添加）'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='detail',
            field=models.ImageField(null=True, upload_to='bracelet/', verbose_name='详细介绍（长图）'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='material',
            field=models.CharField(max_length=50, null=True, verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='symbol',
            field=models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, null=True, verbose_name='寓意'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='cover',
            field=models.ImageField(null=True, upload_to='gemstone/', verbose_name='封面图片（其他图片在下方关联模型里添加）'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='detail',
            field=models.ImageField(null=True, upload_to='gemstone/', verbose_name='详细介绍（长图）'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='material',
            field=models.CharField(max_length=50, null=True, verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='symbol',
            field=models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, null=True, verbose_name='寓意'),
        ),
        migrations.AddField(
            model_name='gift',
            name='cover',
            field=models.ImageField(null=True, upload_to='gift/', verbose_name='封面图片（其他图片在下方关联模型里添加）'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='detail',
            field=models.ImageField(null=True, upload_to='gift/', verbose_name='详细介绍（长图）'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='typ',
            field=models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, verbose_name='寓意'),
        ),
        migrations.CreateModel(
            name='GiftPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='giftpic/', verbose_name='图片')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.gift', verbose_name='对应的挚礼')),
            ],
        ),
        migrations.CreateModel(
            name='GemstonePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='gemstonepic/', verbose_name='图片')),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.gemstone', verbose_name='对应的珠')),
            ],
        ),
        migrations.CreateModel(
            name='BraceletPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='braceletpic/', verbose_name='图片')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bracelet', verbose_name='对应的手链')),
            ],
        ),
    ]
