# Generated by Django 4.2 on 2024-08-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_bracelet_pic_remove_gemstone_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='braceletpic',
            options={'verbose_name': '手链的产品摄影', 'verbose_name_plural': '手链的产品摄影'},
        ),
        migrations.AlterModelOptions(
            name='gemstonepic',
            options={'verbose_name': '珠的产品摄影', 'verbose_name_plural': '珠的产品摄影'},
        ),
        migrations.AlterModelOptions(
            name='giftpic',
            options={'verbose_name': '挚礼的产品摄影', 'verbose_name_plural': '挚礼的产品摄影'},
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='cover',
            field=models.ImageField(null=True, upload_to='bracelet/', verbose_name='封面图片（其他图片在下方产品摄影里添加）'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='cover',
            field=models.ImageField(null=True, upload_to='gemstone/', verbose_name='封面图片（其他图片在下方产品摄影里添加）'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='cover',
            field=models.ImageField(null=True, upload_to='gift/', verbose_name='封面图片（其他图片在下方产品摄影里添加）'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='intro',
            field=models.TextField(verbose_name='介绍'),
        ),
    ]
