# Generated by Django 4.2 on 2024-08-09 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_gemstone_size_alter_gift_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='size',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='尺寸（单位：毫米）'),
        ),
    ]
