# Generated by Django 4.2 on 2024-08-16 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_gemstone_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='尺寸（单位：毫米）'),
        ),
    ]
