# Generated by Django 4.2 on 2024-08-19 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_gemstone_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('typ', models.CharField(choices=[('其他', '其他')], max_length=20, verbose_name='类别')),
                ('symbol', models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, null=True, verbose_name='寓意')),
                ('material', models.CharField(max_length=50, null=True, verbose_name='材料')),
                ('size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='尺寸（单位：毫米）')),
                ('cover', models.ImageField(null=True, upload_to='gemstone/', verbose_name='封面图片（其他图片在下方产品摄影里添加）')),
                ('detail', models.ImageField(null=True, upload_to='gemstone/', verbose_name='详细介绍（长图）')),
                ('loc', models.CharField(max_length=50, verbose_name='产地')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否为推荐商品')),
            ],
            options={
                'verbose_name': '印章',
                'verbose_name_plural': '印章',
            },
        ),
        migrations.AddField(
            model_name='bracelet',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否为推荐商品'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否为推荐商品'),
        ),
        migrations.AddField(
            model_name='gift',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否为推荐商品'),
        ),
        migrations.CreateModel(
            name='StampPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='stamppic/', verbose_name='图片')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.stamp', verbose_name='对应的印章')),
            ],
            options={
                'verbose_name': '印章的产品摄影',
                'verbose_name_plural': '印章的产品摄影',
            },
        ),
    ]
