# Generated by Django 4.2 on 2024-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_stamp_bracelet_is_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='typ',
        ),
        migrations.AddField(
            model_name='bracelet',
            name='wuxing',
            field=models.CharField(choices=[('金', '金'), ('木', '木'), ('水', '水'), ('火', '火'), ('土', '土')], max_length=20, null=True, verbose_name='五行/色系'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='wuxing',
            field=models.CharField(choices=[('金', '金'), ('木', '木'), ('水', '水'), ('火', '火'), ('土', '土')], max_length=20, null=True, verbose_name='五行/色系'),
        ),
        migrations.AddField(
            model_name='gift',
            name='symbol',
            field=models.CharField(choices=[('财运', '财运'), ('姻缘', '姻缘'), ('健康', '健康'), ('学业', '学业'), ('事业', '事业'), ('好运', '好运')], max_length=20, null=True, verbose_name='寓意'),
        ),
        migrations.AddField(
            model_name='gift',
            name='wuxing',
            field=models.CharField(choices=[('金', '金'), ('木', '木'), ('水', '水'), ('火', '火'), ('土', '土')], max_length=20, null=True, verbose_name='五行/色系'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='wuxing',
            field=models.CharField(choices=[('金', '金'), ('木', '木'), ('水', '水'), ('火', '火'), ('土', '土')], max_length=20, null=True, verbose_name='五行/色系'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='cover',
            field=models.ImageField(null=True, upload_to='stamp/', verbose_name='封面图片（其他图片在下方产品摄影里添加）'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='detail',
            field=models.ImageField(null=True, upload_to='stamp/', verbose_name='详细介绍（长图）'),
        ),
    ]
