# Generated by Django 4.2 on 2024-08-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_gift_typ_bracelet_wuxing_gemstone_wuxing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='bracelet/thumbnail/', verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='gemstone/thumbnail/', verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='gift',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='gift/thumbnail/', verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='stamp/thumbnail/', verbose_name='缩略图'),
        ),
    ]
