# Generated by Django 4.2 on 2024-08-21 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_bracelet_thumbnail_gemstone_thumbnail_gift_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)(\\|(财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康|学业|事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (示例：健康|学业|事业)'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)(\\|(财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康|学业|事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (示例：健康|学业|事业)'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)(\\|(财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康|学业|事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (示例：健康|学业|事业)'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)(\\|(财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康|学业|事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (示例：健康|学业|事业)'),
        ),
    ]
