# Generated by Django 4.2 on 2024-08-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_bracelet_symbol_alter_gemstone_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='component',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*(珠|手链)\\[\\d+\\]\\|)*(\\d+\\*(珠|手链)\\[\\d+\\])$', '请用这样的格式来表示产品的组成: 3*珠[1]|2*珠[2|1*手链[1]')], verbose_name='组成\n (示例: 3*塑料石|2*蓝宝石|1*玉髓手环)'),
        ),
    ]
