# Generated by Django 4.2 on 2024-08-21 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_bracelet_symbol_alter_gemstone_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (财运/姻缘/健康/学业/事业/好运, 用空格分隔)'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (财运/姻缘/健康/学业/事业/好运, 用空格分隔)'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (财运/姻缘/健康/学业/事业/好运, 用空格分隔)'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='symbol',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意 (财运/姻缘/健康/学业/事业/好运, 用空格分隔)'),
        ),
    ]
