# Generated by Django 4.2 on 2024-08-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_bracelet_size_alter_bracelet_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='position',
            field=models.CharField(choices=[('顶珠', '顶珠'), ('侧珠', '侧珠'), ('腰珠', '腰珠'), ('子珠', '子珠'), ('配珠', '配珠'), ('其他', '其他')], max_length=20, null=True, verbose_name='位置'),
        ),
    ]
