# Generated by Django 4.2 on 2024-08-23 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_phone'),
        ('product', '0023_gemstone_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='gift',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gift',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='position',
            field=models.CharField(choices=[('顶珠', '顶珠'), ('腰珠', '腰珠'), ('子珠', '子珠'), ('配珠', '配珠'), ('其他', '其他')], max_length=20, null=True, verbose_name='位置'),
        ),
        migrations.CreateModel(
            name='Scheme_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('is_user_defined', models.BooleanField(blank=True, default=False, verbose_name='是否为用户自定义的')),
                ('dingzhu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='顶珠个数')),
                ('yaozhu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='腰珠个数')),
                ('zizhu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='子珠个数')),
                ('peizhu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='配珠个数')),
                ('structure', models.CharField(help_text='从顶珠开始顺时针, 用数字表示该位置的珠子类型, 顶珠-1、腰珠-2、子珠-3、配珠-4', max_length=50, null=True, verbose_name='模板结构描述 (从顶珠开始顺时针, 用数字表示该位置的珠子类型)')),
                ('thumbnail', models.ImageField(null=True, upload_to='scheme/thumbnail/', verbose_name='示意图')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '方案模板',
                'verbose_name_plural': '方案模板',
            },
        ),
    ]
