# Generated by Django 4.2 on 2024-08-23 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_bracelet_create_time_bracelet_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='component',
            field=models.CharField(help_text='请用这样的格式来表示产品的组成: 个数*珠/手链-id 个数*珠/手链-id。例如: 3*珠-1 2*珠-2 1*手链-1', max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*(珠|手链)\\-\\d+ )*(\\d+\\*(珠|手链)\\-\\d+)$', '请用这样的格式来表示产品的组成: 个数*珠/手链-id 个数*珠/手链-id。例如: 3*珠-1 2*珠-2 1*手链-1')], verbose_name='组成 '),
        ),
        migrations.AlterField(
            model_name='gift',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='scheme_template',
            name='structure',
            field=models.CharField(help_text='从顶珠开始顺时针记录, 用数字表示该位置的珠子类型, 空格分隔, 顶珠-1、腰珠-2、子珠-3、配珠-4。 \n                                      例如: 1 2 3 2 3 2 3 2 3 2 3 2 3 2', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^(\\d+\\*(珠|手链)\\-\\d+ )*(\\d+\\*(珠|手链)\\-\\d+)$', '请用这样的格式来表示产品的组成: 个数*珠/手链-id 个数*珠/手链-id。例如: 3*珠-1 2*珠-2 1*手链-1')], verbose_name='模板结构描述'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|好运)( (财运|姻缘|健康|学业|事业|好运))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、好运。')], verbose_name='寓意'),
        ),
    ]
