# Generated by Django 4.2 on 2024-08-23 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_bracelet_symbol_alter_gemstone_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|转运|平安|解忧)( (财运|姻缘|健康|学业|事业|转运|平安|解忧))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|转运|平安|解忧)( (财运|姻缘|健康|学业|事业|转运|平安|解忧))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|转运|平安|解忧)( (财运|姻缘|健康|学业|事业|转运|平安|解忧))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。')], verbose_name='寓意'),
        ),
        migrations.AlterField(
            model_name='scheme_template',
            name='structure',
            field=models.CharField(help_text='从顶珠开始顺时针记录, 用数字表示该位置的珠子类型, 空格分隔, 顶珠-1、腰珠-2、子珠-3、配珠-4。 \n                                      例如: 1 2 3 2 3 2 3 2 3 2 3 2 3 2', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^(1|2|3|4)( (1|2|3|4))*$', '从顶珠开始顺时针记录, 用数字表示该位置的珠子类型, 空格分隔, 顶珠-1、腰珠-2、子珠-3、配珠-4 \n                                      例如: 1 2 3 2 3 2 3 2 3 2 3 2 3 2')], verbose_name='模板结构描述'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='symbol',
            field=models.CharField(help_text='请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(财运|姻缘|健康|学业|事业|转运|平安|解忧)( (财运|姻缘|健康|学业|事业|转运|平安|解忧))*$', '请用这样的格式来表示寓意: 健康 学业 事业。\n可选的寓意有: 财运、姻缘、健康、学业、事业、转运、平安、解忧。')], verbose_name='寓意'),
        ),
    ]
