# Generated by Django 4.2 on 2024-09-02 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_gemstone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='inventory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='inventory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='inventory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='typ',
            field=models.CharField(choices=[('其他', '其他')], max_length=20, verbose_name='类别'),
        ),
    ]
