# Generated by Django 4.2 on 2024-09-03 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_bracelet_inventory_gemstone_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='sales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='sales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='sales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量'),
        ),
    ]
