# Generated by Django 4.2 on 2024-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_bracelet_sales_gemstone_sales_stamp_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='typ',
            field=models.CharField(blank=True, choices=[('宝石', '宝石'), ('其他', '其他')], max_length=20, null=True, verbose_name='类别'),
        ),
    ]
