# Generated by Django 4.2 on 2024-09-03 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_gemstone_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='size',
            field=models.IntegerField(blank=True, help_text='（单位：毫米）', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='尺寸'),
        ),
    ]
