# Generated by Django 4.2 on 2024-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_gift_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='intro_full',
            field=models.TextField(null=True, verbose_name='介绍（55字）'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='intro_mini',
            field=models.TextField(null=True, verbose_name='介绍（15字）'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='intro',
            field=models.TextField(verbose_name='介绍（35字）'),
        ),
    ]
