# Generated by Django 4.2 on 2024-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_gemstone_intro_full_gemstone_intro_mini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='intro_full',
            field=models.TextField(null=True, verbose_name='介绍（55字）'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='intro_mini',
            field=models.TextField(null=True, verbose_name='介绍（15字）'),
        ),
        migrations.AddField(
            model_name='gift',
            name='intro_full',
            field=models.TextField(null=True, verbose_name='介绍（55字）'),
        ),
        migrations.AddField(
            model_name='gift',
            name='intro_mini',
            field=models.TextField(null=True, verbose_name='介绍（15字）'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='intro_full',
            field=models.TextField(null=True, verbose_name='介绍（55字）'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='intro_mini',
            field=models.TextField(null=True, verbose_name='介绍（15字）'),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='intro',
            field=models.TextField(verbose_name='介绍（35字）'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='intro',
            field=models.TextField(verbose_name='介绍（35字）'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='intro',
            field=models.TextField(verbose_name='介绍（35字）'),
        ),
    ]
