# Generated by Django 4.2 on 2024-10-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_bracelet_intro_full_bracelet_intro_mini_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='wuxing',
        ),
        migrations.AddField(
            model_name='gemstone',
            name='photo_12',
            field=models.ImageField(null=True, upload_to='gemstone/1_2/', verbose_name='1:2图片（方案定制时使用）'),
        ),
    ]
