# Generated by Django 4.2 on 2024-07-16 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('discount', models.CharField(max_length=50, verbose_name='折扣方式')),
            ],
            options={
                'verbose_name': '优惠券类型',
                'verbose_name_plural': '优惠券类型',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='总金额')),
                ('ordered_dt', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('paid_dt', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('delivery_dt', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已完成'), (5, '退款/售后')], default=1, verbose_name='订单状态')),
                ('recipient', models.CharField(max_length=15, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('detailed_address', models.TextField(verbose_name='详细地址')),
                ('tracking_number', models.CharField(max_length=255, null=True, verbose_name='快递单号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='退货理由')),
                ('typ', models.IntegerField(choices=[(0, '退货退款'), (1, '换货')], verbose_name='类别')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='refund/', verbose_name='图片')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='所属订单')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddl', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('coupontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coupontype', verbose_name='优惠券类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '优惠券拥有情况',
                'verbose_name_plural': '优惠券拥有情况',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*[^\\|]+\\|)*(\\d+\\*[^\\|]+)$', '请用这样的格式来表示产品的组成: 3*塑料石|2*蓝宝石|1*玉髓手环')], verbose_name='零件组成')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金额')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='是否下单')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='所属订单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
