# Generated by Django 4.2 on 2024-07-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_bracelet_gemstone_gift_delete_component'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='bracelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.bracelet', verbose_name='链'),
        ),
        migrations.AddField(
            model_name='cart',
            name='gemstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.gemstone', verbose_name='珠'),
        ),
        migrations.AddField(
            model_name='cart',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.gift', verbose_name='挚礼'),
        ),
    ]
