# Generated by Django 4.2 on 2024-07-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cart_product_cart_bracelet_cart_gemstone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='typ',
            field=models.CharField(choices=[('挚礼', '挚礼'), ('珠', '珠'), ('手链', '手链')], default='挚礼', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='所属订单'),
        ),
    ]
