# Generated by Django 4.2 on 2024-07-19 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_typ_alter_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='component',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(\\d+\\*[^\\|]+\\|)*(\\d+\\*[^\\|]+)$', '请用这样的格式来表示产品的组成: 3*塑料石|2*蓝宝石|1*玉髓手环')], verbose_name='组成'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='所属订单'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Coupontype',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
