# Generated by Django 4.2 on 2024-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_refund_order_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已完成'), (5, '退款/售后中'), (6, '完成退款/售后')], default=1, verbose_name='订单状态'),
        ),
    ]
