# Generated by Django 4.2 on 2024-08-28 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_advice'),
        ('product', '0027_alter_gemstone_name'),
        ('shop', '0011_alter_cart_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='component',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='typ',
        ),
        migrations.AddField(
            model_name='cart',
            name='group_type',
            field=models.CharField(blank=True, choices=[('散件', '散件'), ('挚礼', '挚礼'), ('方案', '方案')], default='散件', max_length=20, null=True, verbose_name='组合类型'),
        ),
        migrations.AddField(
            model_name='cart',
            name='letter',
            field=models.CharField(blank=True, choices=[('散件', '散件'), ('挚礼', '挚礼'), ('方案', '方案')], default='散件', max_length=20, null=True, verbose_name='自定义文字（目前只有印章用的到）'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_type',
            field=models.CharField(choices=[('珠', '珠'), ('手链', '手链'), ('印章', '印章')], default='珠', max_length=20, verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='cart',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.stamp', verbose_name='印章'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.IntegerField(choices=[(0, '不需要'), (1, '免费提供'), (2, '付费购买')], default=0, verbose_name='包装'),
        ),
        migrations.AddField(
            model_name='order',
            name='self_design',
            field=models.BooleanField(default=False, verbose_name='是否自己设计'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bracelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.bracelet', verbose_name='链'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='gemstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gemstone', verbose_name='珠'),
        ),
        migrations.CreateModel(
            name='CartGroupScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('方案模板', '方案模板'), ('方案随心自选', '方案随心自选')], default='挚礼', max_length=20, verbose_name='类别')),
                ('gem_location', models.CharField(help_text='从顶珠开始顺时针记录, 用珠id表示该位置是什么珠子, 空格分隔\n                                      例如: 4 5 7 5 7 5 11 11 11 5 7 5 7 5', max_length=200, validators=[django.core.validators.RegexValidator('^\\d+( \\d+)*$', '从顶珠开始顺时针记录, 用数字表示该位置的珠子类型, 空格分隔, 顶珠-1、腰珠-2、子珠-3、配珠-4 \n                                      例如: 1 2 3 2 3 2 3 2 3 2 3 2 3 2')], verbose_name='珠位置描述')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.gift', verbose_name='方案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='CartGroupGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.gift', verbose_name='挚礼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='gift_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cartgroupgift', verbose_name='挚礼'),
        ),
        migrations.AddField(
            model_name='cart',
            name='scheme_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cartgroupscheme', verbose_name='方案'),
        ),
    ]
