# Generated by Django 4.2 on 2024-08-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartgroupgift',
            options={'verbose_name': '购物车组合-挚礼', 'verbose_name_plural': '购物车组合-挚礼'},
        ),
        migrations.AlterModelOptions(
            name='cartgroupscheme',
            options={'verbose_name': '购物车组合-方案', 'verbose_name_plural': '购物车组合-方案'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='group_type',
            field=models.CharField(choices=[('散件', '散件'), ('挚礼', '挚礼'), ('方案', '方案')], default='散件', max_length=20, verbose_name='组合类型'),
        ),
        migrations.AlterField(
            model_name='cartgroupscheme',
            name='typ',
            field=models.CharField(choices=[('基于模板', '基于模板'), ('随心自选', '随心自选')], default='挚礼', max_length=20, verbose_name='类别'),
        ),
    ]
