# Generated by Django 4.2 on 2024-09-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cartgroupgift_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgroupgift',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='cartgroupscheme',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
