# Generated by Django 4.2 on 2024-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartgroupgift_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgroupscheme',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名'),
        ),
    ]
