# Generated by Django 4.2 on 2024-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cartgroupscheme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.CharField(choices=[('不需要', '不需要'), ('免费提供', '免费提供'), ('付费购买', '付费购买')], default='不需要', max_length=10, verbose_name='包装'),
        ),
    ]
