# Generated by Django 4.2 on 2024-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evalreport',
            options={'verbose_name': '测评报告', 'verbose_name_plural': '测评报告'},
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question1',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], verbose_name='问题1'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question2',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], verbose_name='问题2'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question3',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], verbose_name='问题3'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question4',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], verbose_name='问题4'),
        ),
    ]
