# Generated by Django 4.2 on 2024-07-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_evalreport_options_alter_evalcontent_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcontent',
            name='wish',
            field=models.CharField(max_length=9, verbose_name='心愿'),
        ),
    ]
