# Generated by Django 4.2 on 2024-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_evalcontent_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='talker',
            field=models.IntegerField(choices=[(0, '大模型'), (1, '用户'), (2, 'sys')], verbose_name='说话人'),
        ),
    ]
