# Generated by Django 4.2 on 2024-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_alter_chathistory_talker'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalcontent',
            name='bazi',
            field=models.CharField(default='壬午 己酉 辛丑 丁酉', max_length=200, verbose_name='八字'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='name',
            field=models.CharField(max_length=15, verbose_name='被测人姓名'),
        ),
    ]
