# Generated by Django 4.2 on 2024-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_alter_evalcontent_bazi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='talker',
            field=models.IntegerField(choices=[(0, '大模型'), (1, '用户')], verbose_name='说话人'),
        ),
    ]
