# Generated by Django 4.2 on 2024-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_alter_chathistory_talker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='msg',
            field=models.CharField(max_length=3000, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='evalreport',
            name='advice',
            field=models.CharField(max_length=1000, verbose_name='建议'),
        ),
        migrations.AlterField(
            model_name='evalreport',
            name='overall',
            field=models.CharField(max_length=2000, verbose_name='整体解读'),
        ),
        migrations.AlterField(
            model_name='evalreport',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='evalreport',
            name='wish',
            field=models.CharField(max_length=1000, verbose_name='心愿'),
        ),
    ]
