# Generated by Django 4.2 on 2024-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_alter_chathistory_msg_alter_evalreport_advice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcontent',
            name='belief',
            field=models.IntegerField(choices=[(0, '其他'), (1, '佛教')], null=True, verbose_name='信仰'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='birthloc',
            field=models.CharField(max_length=30, null=True, verbose_name='出生地'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='job',
            field=models.CharField(max_length=15, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='liveloc',
            field=models.CharField(max_length=30, null=True, verbose_name='现居地'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='mood',
            field=models.IntegerField(choices=[(0, '好'), (1, '一般'), (2, '不好')], null=True, verbose_name='心情'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question1',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], null=True, verbose_name='问题1'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question2',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], null=True, verbose_name='问题2'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question3',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], null=True, verbose_name='问题3'),
        ),
        migrations.AlterField(
            model_name='evalcontent',
            name='question4',
            field=models.IntegerField(choices=[(1, '选项一'), (2, '选项二')], null=True, verbose_name='问题4'),
        ),
    ]
