# Generated by Django 4.2 on 2024-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_alter_evalcontent_belief_alter_evalcontent_birthloc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalreport',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='evalreport',
            name='wish',
        ),
        migrations.AddField(
            model_name='evalreport',
            name='overall_1',
            field=models.CharField(default='......', max_length=2000, verbose_name='整体解读-关键词1'),
        ),
        migrations.AddField(
            model_name='evalreport',
            name='overall_2',
            field=models.CharField(default='......', max_length=2000, verbose_name='整体解读-关键词2'),
        ),
        migrations.AddField(
            model_name='evalreport',
            name='overall_3',
            field=models.CharField(default='......', max_length=2000, verbose_name='整体解读-关键词3'),
        ),
    ]
