# Generated by Django 4.2 on 2024-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_remove_evalreport_overall_remove_evalreport_wish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalreport',
            name='advice',
            field=models.CharField(max_length=1000, null=True, verbose_name='建议'),
        ),
    ]
