# Generated by Django 4.2 on 2024-09-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_advice'),
        ('llm', '0011_alter_evalreport_advice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evalcontent',
            unique_together={('user', 'name', 'forself')},
        ),
    ]
