# Generated by Django 4.2 on 2024-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_alter_evalcontent_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalreport',
            name='advice',
        ),
        migrations.AddField(
            model_name='evalreport',
            name='wish_1',
            field=models.CharField(max_length=1000, null=True, verbose_name='心愿解读-1'),
        ),
        migrations.AddField(
            model_name='evalreport',
            name='wish_2',
            field=models.CharField(max_length=1000, null=True, verbose_name='心愿解读-2'),
        ),
        migrations.AddField(
            model_name='evalreport',
            name='wish_3',
            field=models.CharField(max_length=1000, null=True, verbose_name='心愿解读-3'),
        ),
    ]
