# Generated by Django 4.2 on 2024-09-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_advice_reason'),
        ('llm', '0013_remove_evalreport_advice_evalreport_wish_1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evalcontent',
            unique_together={('user', 'name')},
        ),
    ]
