# Generated by Django 4.2 on 2024-09-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_advice'),
        ('llm', '0015_advice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advice',
            unique_together={('user', 'person_name', 'gem_name')},
        ),
    ]
