# Generated by Django 4.2 on 2024-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0016_alter_advice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
