# Generated by Django 4.2 on 2024-07-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=28, unique=True, verbose_name='openid')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('birthdt', models.DateTimeField(blank=True, null=True, verbose_name='出生时间')),
                ('birthloc', models.CharField(blank=True, max_length=30, null=True, verbose_name='出生地')),
                ('liveloc', models.CharField(blank=True, max_length=30, null=True, verbose_name='现居地')),
                ('job', models.CharField(blank=True, max_length=15, null=True, verbose_name='职业')),
                ('belief', models.IntegerField(blank=True, choices=[(0, '其他'), (1, '佛教')], null=True, verbose_name='信仰')),
                ('mbti', models.CharField(blank=True, max_length=4, null=True, verbose_name='MBTI')),
                ('identity', models.IntegerField(blank=True, choices=[(0, '普通'), (1, 'VIP')], null=True, verbose_name='用户身份')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
