# Generated by Django 4.2 on 2024-07-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesstoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024, unique=True)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=28, unique=True, verbose_name='openid')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('birthdt', models.DateTimeField(blank=True, null=True, verbose_name='出生时间')),
                ('birthloc', models.CharField(blank=True, max_length=30, null=True, verbose_name='出生地')),
                ('liveloc', models.CharField(blank=True, max_length=30, null=True, verbose_name='现居地')),
                ('job', models.CharField(blank=True, max_length=15, null=True, verbose_name='职业')),
                ('belief', models.IntegerField(blank=True, choices=[(0, '其他'), (1, '佛教')], null=True, verbose_name='信仰')),
                ('mbti', models.CharField(blank=True, max_length=4, null=True, verbose_name='MBTI')),
                ('identity', models.IntegerField(choices=[(0, '普通'), (1, 'VIP')], default=0, verbose_name='用户身份')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=15, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('detailed_address', models.TextField(verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
    ]
