# Generated by Django 4.2 on 2024-09-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='reason',
            field=models.CharField(default='', max_length=1000, verbose_name='解释'),
        ),
    ]
