# Generated by Django 4.2 on 2024-09-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_advice_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advice',
        ),
    ]
